### ISSUE TITLE
Consider using String.codeUnits instead of utf8.encode?

### ISSUE THREAD

**Issue by shyndman** [Midi12/fnv#1]
Hi there,

Thanks for the package.

I noticed that the package hashes strings by UTF8 encoding them first. Have you considered using [`String.codeUnits`](https://api.flutter.dev/flutter/dart-core/String/codeUnits.html) instead?

`codeUnits` is the string's backing data structure, so nothing has to be computed. I put together a quick benchmark and it's considerably faster:

https://gist.github.com/shyndman/3b73ec340fa6e4ea8e4b510bf9bb0d3f

**Comment by Midi12** [comment]
Hello,

Thanks for opening this issue.

I've considered using the `codeUnits` when writing this library.

The `codeUnits` property is a UTF-16 representation of the string. The Fowler–Noll–Vo hash input is an array of *8-bit unsigned integer*. The `codeUnits` property could then return a list of integers in the [0, 2**16 - 1] range which would invalidate the FNV hash algorithm.

Converting a "wide string" to UTF-8 and then getting the backing char array (`utf8.encode` works on the backing data structure) is the shortest path I can think of in terms of correctness and performance.

While you are right on the overhead induced by the UTF-8 encoding for the string-based API (`fnv1_32_s`, `fnv1a_32_s`, `fnv1_64_s`, `fnv1a_64_s`) you can use the integer list based API (`fnv1_32_s`, `fnv1a_32_s`, `fnv1_64_s`, `fnv1a_64_s`) if your library works on byte arrays.

I am closing this issue.

**Comment by shyndman** [comment]
Ah, interesting, thanks.
